"""AI introspection endpoints: health, model evaluation, duplicate detection.

Registered by ``app.api.v1.router``'s optional-module loader.

Note on ``/complaints/{id}/duplicates``: that contract path is already served by
``app.api.v1.complaints``, which is included *before* the optional routers, so
registering the same path here would create a shadowed, unreachable duplicate
route and two conflicting OpenAPI operations. The TF-IDF engine is therefore
exposed at ``/ai/duplicates/{complaint_id}`` instead, and
``app.ai.duplicates.find_duplicates`` is importable so ``ComplaintManager`` can
delegate to it and keep exactly one implementation behind the contract path.
"""

from __future__ import annotations

import contextlib
import json
from pathlib import Path
from typing import Annotated, Any

from fastapi import APIRouter, Query

from app.core.errors import NotFoundError
from app.core.logging_config import get_logger

router = APIRouter(tags=["ai"])
log = get_logger(__name__)

#: Backend package root: app/api/v1/ai.py -> v1 -> api -> app -> <root>
_ROOT = Path(__file__).resolve().parents[3]
_ARTIFACTS = _ROOT / "ml" / "artifacts"


@router.get("/ai/health", summary="Analyzer tier availability")
async def ai_health() -> dict[str, Any]:
    """Which analyzer tiers are live right now, and why.

    Deliberately does no network I/O — it reports configuration and circuit-breaker
    state, not a live probe, so it stays fast and cannot itself be the thing that
    hangs during an outage. Superset of the contract's ``AIHealthResponse``.
    """
    try:
        from app.ai.pipeline import health_snapshot
    except Exception as exc:  # noqa: BLE001 - health must answer even if AI is broken
        log.error("ai.health_import_failed", error=str(exc))
        return {
            "llm_available": False, "ml_model_loaded": False, "rules_available": False,
            "model_name": "", "last_error": f"AI layer failed to import: {exc}",
        }
    try:
        return health_snapshot()
    except Exception as exc:  # noqa: BLE001
        log.error("ai.health_failed", error=str(exc))
        return {
            "llm_available": False, "ml_model_loaded": False, "rules_available": True,
            "model_name": "keyword-rules-v1", "last_error": str(exc),
        }


@router.get("/ai/evaluation", summary="Stored model-evaluation report")
async def ai_evaluation(
    format: Annotated[str, Query(pattern="^(json|markdown|both)$")] = "both",
) -> dict[str, Any]:
    """Serve ``ml/artifacts/evaluation.md`` plus the machine-readable metrics.

    These are generated offline by ``python -m ml.evaluate`` and committed. Nothing
    is trained or evaluated at request time.
    """
    metrics_path = _ARTIFACTS / "metrics.json"
    report_path = _ARTIFACTS / "evaluation.md"
    metadata_path = _ARTIFACTS / "metadata.json"

    if not metrics_path.exists() and not report_path.exists():
        raise NotFoundError(
            "No evaluation report has been generated. Run `python -m ml.train` "
            "followed by `python -m ml.evaluate`."
        )

    payload: dict[str, Any] = {
        "available": True,
        "artifacts_dir": str(_ARTIFACTS),
        "confusion_matrix_images": [
            p.name for p in sorted(_ARTIFACTS.glob("confusion_*.png"))
        ],
    }

    if format in {"json", "both"} and metrics_path.exists():
        try:
            payload["metrics"] = json.loads(metrics_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            payload["metrics_error"] = str(exc)

    if metadata_path.exists():
        with contextlib.suppress(OSError, json.JSONDecodeError):
            payload["training_metadata"] = json.loads(metadata_path.read_text(encoding="utf-8"))

    if format in {"markdown", "both"} and report_path.exists():
        try:
            payload["report_markdown"] = report_path.read_text(encoding="utf-8")
        except OSError as exc:
            payload["report_error"] = str(exc)

    # Stated on every response, not buried in the markdown: the headline accuracy
    # comes from synthetic data and is an upper bound.
    payload["honesty_note"] = (
        "The model was trained on synthetic data generated by ml/generate_dataset.py. "
        "The held-out split uses different sentence templates from training, so the "
        "score is not pure memorisation — but it is still an upper bound on real-world "
        "accuracy, not a prediction of it. This is why the ML model is the fallback "
        "tier rather than the primary analyzer."
    )
    return payload


@router.get("/ai/duplicates/{complaint_id}", summary="TF-IDF duplicate candidates")
async def duplicates_for_complaint(
    complaint_id: str,
    limit: Annotated[int, Query(ge=1, le=20)] = 5,
    radius_m: Annotated[float, Query(ge=50, le=20000)] = 500.0,
    window_days: Annotated[int, Query(ge=1, le=365)] = 30,
    threshold: Annotated[float, Query(ge=0.0, le=1.0)] = 0.55,
) -> dict[str, Any]:
    """Ranked duplicate candidates: same category, within ``radius_m``, ``window_days``.

    Returns the contract's ``{candidates:[{complaint, similarity, reason}]}`` shape
    with two extra diagnostic fields (``relation``, ``distance_m``).
    """
    from app.ai.duplicates import DUPLICATE_THRESHOLD, RELATED_THRESHOLD, find_duplicates
    from app.schemas.complaint import ComplaintRead

    candidates = await find_duplicates(
        complaint_id, limit=limit, radius_m=radius_m,
        window_days=window_days, threshold=threshold,
    )

    def _serialise(complaint: Any) -> dict[str, Any]:
        return ComplaintRead.model_validate(complaint).model_dump(mode="json")

    return {
        "candidates": [c.to_dict(_serialise) for c in candidates],
        "thresholds": {"duplicate": DUPLICATE_THRESHOLD, "related": RELATED_THRESHOLD},
        "method": (
            "TF-IDF cosine similarity (word 1-2gram + char_wb 3-5gram) over complaints "
            f"in the same category from the last {window_days} days, geographically "
            f"gated to {int(radius_m)} m when both complaints have coordinates. "
            "Lexical, not semantic: two people describing the same issue with entirely "
            "different words will not match."
        ),
    }
