"""Pydantic wire schemas — the serialisation boundary of the API."""

from app.schemas.ai import (
    AIAnalysisRead,
    AIAnalysisResult,
    AIHealthResponse,
    AnalyzePreviewRequest,
    DuplicateCandidate,
    DuplicatesResponse,
)
from app.schemas.common import (
    AISource,
    AIStatus,
    Category,
    ErrorBody,
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    MessageResponse,
    ORMModel,
    Page,
    Priority,
    Role,
    Sentiment,
    SortField,
    SortOrder,
    Status,
)
from app.schemas.complaint import (
    ComplaintCreate,
    ComplaintDetail,
    ComplaintFilters,
    ComplaintRead,
    ComplaintUpdate,
    StatusEventRead,
)
from app.schemas.department import DepartmentCreate, DepartmentRead, DepartmentRef
from app.schemas.user import LoginRequest, TokenResponse, UserCreate, UserRead

__all__ = [
    "AIAnalysisRead",
    "AIAnalysisResult",
    "AIHealthResponse",
    "AISource",
    "AIStatus",
    "AnalyzePreviewRequest",
    "Category",
    "ComplaintCreate",
    "ComplaintDetail",
    "ComplaintFilters",
    "ComplaintRead",
    "ComplaintUpdate",
    "DepartmentCreate",
    "DepartmentRead",
    "DepartmentRef",
    "DuplicateCandidate",
    "DuplicatesResponse",
    "ErrorBody",
    "ErrorDetail",
    "ErrorResponse",
    "HealthResponse",
    "LoginRequest",
    "MessageResponse",
    "ORMModel",
    "Page",
    "Priority",
    "Role",
    "Sentiment",
    "SortField",
    "SortOrder",
    "Status",
    "StatusEventRead",
    "TokenResponse",
    "UserCreate",
    "UserRead",
]
