"""Local scikit-learn tier — the offline fallback that keeps the product working.

INPUT      raw complaint text (English / Roman-Urdu / code-switched).
PROCESSING TF-IDF over word 1-2 grams unioned with char_wb 3-5 grams, then two
           calibrated LinearSVC heads (category, priority) trained offline by
           ``ml/train.py``. Artifacts are loaded from disk on first use and cached
           in a module singleton. No network, no downloads, ~0.15 ms per document.
OUTPUT     an :class:`AnalysisResult` with ``source="ml"`` and a genuine
           Platt-scaled probability as ``confidence``.

LIMITATIONS — see ``ml/artifacts/evaluation.md`` for the measured numbers
    * **Trained entirely on synthetic data** generated by ``ml/generate_dataset.py``.
      Held-out accuracy (disjoint sentence frames) is ~0.76 for category and ~0.74
      for priority. That is an **upper bound**: real complaints are ambiguous in a
      way the generator cannot simulate, so expect materially worse on real traffic.
      This is exactly why this tier sits *below* the LLM in the fallback chain.
    * No semantics. TF-IDF cannot tell that an unseen word is a synonym of a seen
      one, so out-of-vocabulary phrasing degrades sharply.
    * No Urdu-script coverage in training data; such complaints get almost no
      usable char n-grams and the prediction approaches a guess.
    * Produces no real summary. It returns a template sentence built from the
      predicted class plus the first clause of the complaint — honest, but not the
      operator-grade summary the LLM writes.
    * Karachi-specific vocabulary; will not transfer to another city.
    * Cannot detect novel emergencies. ``is_emergency`` is derived from the
      predicted priority plus a small keyword check, not from understanding.
"""

from __future__ import annotations

import logging
import re
import threading
import time
from pathlib import Path
from typing import Any

from app.ai.base import (
    DEPARTMENT_BY_CATEGORY,
    AIAnalyzer,
    AnalysisResult,
    AnalyzerUnavailable,
)

logger = logging.getLogger("app.ai.ml")

MODEL_FILENAME = "model.joblib"

#: A handful of unambiguous emergency markers. The model predicts priority; this
#: only ever *raises* it, never lowers it. Under-triage is the expensive error.
_EMERGENCY_RE = re.compile(
    r"\b(electric(?:\s|-)?shock|electrocut\w*|current\s+(?:laga|aa\s*raha)|live\s+wire|"
    r"gas\s+leak|explosion|fire\s+brigade|collaps\w+|died|death|dead\s+body|"
    r"fatal|ambulance|emergency|hospitalis\w+|hospitaliz\w+|injur\w+|"
    r"zakhmi|hadsa|jaan\s+ka\s+khatra|khatarnak|bachao)\b",
    re.IGNORECASE,
)

_STOPWORDS = {
    "the", "and", "for", "with", "that", "this", "has", "have", "been", "are",
    "was", "were", "from", "our", "not", "there", "they", "very", "please",
    "kindly", "sir", "here", "which", "since", "into", "out", "all", "any",
    "hai", "hain", "ka", "ki", "ke", "me", "mein", "se", "par", "aur", "bohot",
    "bhi", "nahi", "kar", "raha", "rahi", "gaya", "gayi", "hum", "hamari",
}


class _ModelBundle:
    """Loaded artifacts. One instance per process, guarded by a lock."""

    def __init__(self, bundle: dict[str, Any], path: Path) -> None:
        self.path = path
        self.category_pipe = bundle["category"]
        self.priority_pipe = bundle["priority"]
        self.model_name: str = bundle.get("model_name", "tfidf-linearsvc-v1")
        self.trained_at: str | None = bundle.get("trained_at")
        self.sklearn_version: str | None = bundle.get("sklearn_version")
        self.categories: list[str] = list(bundle.get("categories", []))
        self.priorities: list[str] = list(bundle.get("priorities", []))


_bundle: _ModelBundle | None = None
_load_lock = threading.Lock()
_load_error: str | None = None
_load_attempted = False


def _repo_root() -> Path:
    """Backend package root: app/ai/ml_analyzer.py -> app/ai -> app -> <root>."""
    return Path(__file__).resolve().parents[2]


def _candidate_paths() -> list[Path]:
    """Every place the artifact might legitimately be, in priority order.

    ``ML_MODEL_PATH`` is honoured first, but it is resolved tolerantly: it may name
    a file or a directory, and it may be relative to the process CWD or to the
    backend root (those differ between ``uvicorn`` from the repo root and Render's
    working directory). If the configured filename does not exist we also look for
    ``model.joblib`` beside it, because the setting's default filename and the name
    ``ml/train.py`` writes are allowed to drift.
    """
    from app.core.config import settings

    root = _repo_root()
    candidates: list[Path] = []
    configured = getattr(settings, "ML_MODEL_PATH", None)
    if configured:
        raw = Path(str(configured)).expanduser()
        for base in ([raw] if raw.is_absolute() else [root / raw, Path.cwd() / raw]):
            candidates.append(base / MODEL_FILENAME if base.is_dir() else base)
            if not base.is_dir():
                candidates.append(base.parent / MODEL_FILENAME)
    candidates.append(root / "ml" / "artifacts" / MODEL_FILENAME)
    candidates.append(Path.cwd() / "ml" / "artifacts" / MODEL_FILENAME)

    seen: set[Path] = set()
    ordered: list[Path] = []
    for c in candidates:
        if c not in seen:
            seen.add(c)
            ordered.append(c)
    return ordered


def _resolve_model_path() -> Path:
    """First candidate that exists, else the first candidate (for the error message)."""
    candidates = _candidate_paths()
    for path in candidates:
        if path.exists():
            return path
    return candidates[0]


def load_model(force: bool = False) -> _ModelBundle | None:
    """Load artifacts once, lazily, thread-safely. Returns None if unavailable.

    Never raises: a missing artifact is an expected state (fresh clone, model not
    committed), and it must degrade to the rules tier rather than break the app.
    """
    global _bundle, _load_error, _load_attempted

    if _bundle is not None and not force:
        return _bundle
    with _load_lock:
        if _bundle is not None and not force:
            return _bundle
        if _load_attempted and not force:
            return _bundle

        _load_attempted = True
        path = _resolve_model_path()
        try:
            if not path.exists():
                _load_error = f"model artifact not found at {path}"
                logger.warning("%s — ML tier disabled, falling back to rules", _load_error)
                return None
            import joblib

            t0 = time.perf_counter()
            raw = joblib.load(path)
            if not isinstance(raw, dict) or "category" not in raw or "priority" not in raw:
                _load_error = f"unexpected artifact structure in {path}"
                logger.error(_load_error)
                return None
            _bundle = _ModelBundle(raw, path)
            _load_error = None
            logger.info(
                "loaded ML model %s from %s in %.0f ms",
                _bundle.model_name, path, 1000 * (time.perf_counter() - t0),
            )
            return _bundle
        except Exception as exc:  # noqa: BLE001
            _load_error = f"{type(exc).__name__}: {exc}"
            logger.exception("failed to load ML model from %s", path)
            return None


def model_status() -> dict[str, Any]:
    """Non-loading status probe for ``GET /ai/health``."""
    path = _resolve_model_path()
    loaded = _bundle is not None
    return {
        "loaded": loaded,
        "path": str(path),
        "artifact_present": path.exists(),
        "model_name": _bundle.model_name if loaded else None,
        "trained_at": _bundle.trained_at if loaded else None,
        "sklearn_version": _bundle.sklearn_version if loaded else None,
        "load_error": _load_error,
    }


def _extract_keywords(text: str, limit: int = 6) -> list[str]:
    """Cheap signal extraction: longest non-stopword tokens, order preserved."""
    tokens = re.findall(r"[A-Za-z؀-ۿ][\w'-]{2,}", text.lower())
    seen: set[str] = set()
    picked: list[tuple[int, str]] = []
    for idx, tok in enumerate(tokens):
        if tok in _STOPWORDS or tok in seen or len(tok) < 4:
            continue
        seen.add(tok)
        picked.append((idx, tok))
    picked.sort(key=lambda p: (-len(p[1]), p[0]))
    return [t for _, t in picked[:limit]]


def _summarise(text: str, category: str, priority: str) -> str:
    """Template summary. Deliberately obvious that no language model wrote it."""
    from app.ai.base import CATEGORY_LABELS

    cleaned = re.sub(r"\s+", " ", (text or "").strip())
    first = re.split(r"(?<=[.!?])\s+", cleaned)[0] if cleaned else ""
    if len(first) > 160:
        first = first[:157].rstrip() + "..."
    label = CATEGORY_LABELS.get(category, category)
    if not first:
        return f"{label} issue, {priority} priority."
    return f"{label} issue ({priority} priority): {first}"


class MLAnalyzer(AIAnalyzer):
    """Concrete :class:`AIAnalyzer` backed by the locally trained sklearn model.

    Inherits the result schema, normalisation and failure handling; overrides
    availability (artifacts must exist) and the prediction itself.
    """

    name = "tfidf-linearsvc-v1"
    source = "ml"

    def __init__(self, eager: bool = False) -> None:
        # Loading is lazy by default: importing this module must never pay the
        # disk + joblib cost, and a missing artifact must never break startup.
        if eager:
            load_model()

    def is_available(self) -> bool:
        return load_model() is not None

    def analyze(self, text: str, context: dict[str, Any] | None = None) -> AnalysisResult:
        bundle = load_model()
        if bundle is None:
            raise AnalyzerUnavailable(_load_error or "ML artifacts unavailable")

        started = time.perf_counter()
        clean = re.sub(r"\s+", " ", (text or "").strip())
        if not clean:
            raise AnalyzerUnavailable("empty complaint text")
        docs = [clean]

        cat_proba = bundle.category_pipe.predict_proba(docs)[0]
        cat_classes = list(bundle.category_pipe.classes_)
        cat_idx = int(cat_proba.argmax())
        category = str(cat_classes[cat_idx])
        cat_conf = float(cat_proba[cat_idx])

        pri_proba = bundle.priority_pipe.predict_proba(docs)[0]
        pri_classes = list(bundle.priority_pipe.classes_)
        pri_idx = int(pri_proba.argmax())
        priority = str(pri_classes[pri_idx])
        pri_conf = float(pri_proba[pri_idx])

        # Runner-up gap tells us whether the decision was close. Useful in the
        # reasoning string and honest about what the model actually did.
        ordered = sorted(zip(cat_classes, cat_proba, strict=False), key=lambda p: -p[1])
        runner_up, runner_conf = (ordered[1] if len(ordered) > 1 else ("-", 0.0))

        # --- escalate-only safety net -------------------------------------
        # The priority head is the weakest part of this model: it was trained on
        # formulaic escalation clauses and it under-triages real text (a leaning
        # pole with live wires over standing water where children play came back
        # as `low` in testing). The deterministic rules engine has a far richer
        # hazard lexicon, including Roman-Urdu.
        #
        # So the rules tier is allowed to RAISE the ML priority and never to lower
        # it. Under-triage can get someone hurt; over-triage wastes a site visit.
        # The category prediction is untouched — that is what the model is good at.
        model_priority = priority
        escalation_note = ""
        try:
            from app.ai.base import PRIORITY_RANK
            from app.ai.rule_analyzer import RuleBasedAnalyzer

            rules_priority, _score, rules_emergency, signals = (
                RuleBasedAnalyzer().score_priority(clean)
            )
            if PRIORITY_RANK[rules_priority] > PRIORITY_RANK[priority]:
                escalation_note = (
                    f" Priority escalated from '{priority}' to '{rules_priority}' by the"
                    f" deterministic hazard rules"
                    + (f" ({', '.join(signals[:3])})" if signals else "")
                    + "; the rules may only raise priority, never lower it."
                )
                priority = rules_priority
                pri_conf = max(pri_conf, 0.55)
                if rules_emergency:
                    pri_conf = max(pri_conf, 0.6)
        except Exception:  # noqa: BLE001 - the safety net must never break analysis
            logger.exception("priority escalation check failed")

        is_emergency = priority == "critical"
        if _EMERGENCY_RE.search(clean) and priority != "critical":
            priority, is_emergency = "critical", True
            pri_conf = max(pri_conf, 0.55)
            escalation_note += " Emergency keyword detected, raised to critical."

        reasoning = (
            f"Local TF-IDF + LinearSVC model. Category '{category}' at "
            f"p={cat_conf:.2f} (runner-up '{runner_up}' p={runner_conf:.2f}); "
            f"priority model predicted '{model_priority}' at p={pri_conf:.2f}."
            + escalation_note
        )
        if cat_conf < 0.45:
            reasoning += (
                " Confidence is low — the wording is outside the model's training"
                " vocabulary, so this classification should be reviewed."
            )

        return AnalysisResult(
            category=category,
            priority=priority,
            summary=_summarise(clean, category, priority),
            department_suggestion=DEPARTMENT_BY_CATEGORY.get(category, "General Administration"),
            # The reported confidence is the category probability, since category
            # is what routing depends on.
            confidence=cat_conf,
            source="ml",
            model_name=bundle.model_name,
            reasoning=reasoning,
            keywords=_extract_keywords(clean),
            # The model has no sentiment head; claiming one would be a lie.
            sentiment=None,
            is_emergency=is_emergency,
            latency_ms=max(0, int((time.perf_counter() - started) * 1000)),
        )

    def predict_proba(self, text: str) -> dict[str, dict[str, float]]:
        """Full probability distributions. Used by the evidence harness and tests."""
        bundle = load_model()
        if bundle is None:
            raise AnalyzerUnavailable(_load_error or "ML artifacts unavailable")
        docs = [re.sub(r"\s+", " ", (text or "").strip())]
        return {
            "category": {
                str(c): round(float(p), 4)
                for c, p in zip(bundle.category_pipe.classes_,
                                bundle.category_pipe.predict_proba(docs)[0], strict=False)
            },
            "priority": {
                str(c): round(float(p), 4)
                for c, p in zip(bundle.priority_pipe.classes_,
                                bundle.priority_pipe.predict_proba(docs)[0], strict=False)
            },
        }
